name: CI

on:
  push:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v5

      - name: Lint
        run: uvx ruff check

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup xpod-chromium
        run: |
          git clone https://github.com/unitehenry/xpod
          docker build -t xpod-base -f xpod/base/Containerfile xpod/base
          docker build -t xpod-chromium -f xpod/apps/chromium/Containerfile xpod/apps/chromium

      - name: Start xpod-chromium
        run: |
          docker run -d \
          --cap-add=SYS_ADMIN \
          -e VNC_PASSWORD="vncpass" \
          -p 5900:5900 \
          -p 9222:9222 \
          --name xpod-chromium \
          xpod-chromium
          sleep 8

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build container
        run: docker build -f Containerfile -t agent-browser-mcp .

      - name: Run image
        run: |
          docker run -d -e CDP_PORT=9222 --name test agent-browser-mcp
          sleep 3

      - name: Cleanup
        run: |
          docker stop xpod-chromium
          docker stop test
          docker rm xpod-chromium
          docker rm test
