name: CI

on:
  push:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v5

      - name: Lint
        run: uvx ruff check

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup docker network
        run: docker network create mcp

      - name: Setup xpod-chromium
        run: |
          git clone https://github.com/unitehenry/xpod
          docker build -t xpod-base -f xpod/base/Containerfile xpod/base
          docker build -t xpod-chromium -f xpod/apps/chromium/Containerfile xpod/apps/chromium

      - name: Start xpod-chromium
        run: |
          docker run -d \
            --network=mcp \
            --cap-add=SYS_ADMIN \
            -e VNC_PASSWORD="vncpass" \
            --name xpod-chromium \
            xpod-chromium
          sleep 8

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build container
        run: docker build -f Containerfile -t agent-browser-mcp .

      - name: Run image
        run: |
          docker run -d \
            --network=mcp \
            -e CDP_PORT="http://$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' xpod-chromium):9222" \
            -p 127.0.0.1:8000:8000 \
            --name agent-browser-mcp \
            agent-browser-mcp
          sleep 3

      - name: Setup uv
        uses: astral-sh/setup-uv@v5

      - name: Install FastMCP CLI
        run: uv pip install fastmcp

      - name: Open Page
        run: fastmcp call http://127.0.0.1:8000/sse agent_browser_open url=google.com

      - name: Cleanup
        run: |
          docker stop xpod-chromium
          docker stop test
          docker rm xpod-chromium
          docker rm test
          docker network rm mcp
